# Generated by Django 4.1.2 on 2022-11-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Categoria Ocupacional',
                'verbose_name_plural': 'Categorias Ocupacionales',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='FuenteProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Fuente de Procedencia',
                'verbose_name_plural': 'Fuentes de Procedencia',
            },
        ),
        migrations.CreateModel(
            name='GrupoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Grupo Escala',
            },
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Motivo de Baja',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='NivelPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Nivel de Preparacion',
                'verbose_name_plural': 'Niveles de Preparacion',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Res272006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Resolucion 272006',
            },
        ),
        migrations.CreateModel(
            name='Res492019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Resolucion 492019',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.municipio')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.unidad')),
            ],
            options={
                'verbose_name': 'Unidad Organizativa',
                'verbose_name_plural': 'Unidades Organizativas',
            },
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('necesarios', models.IntegerField()),
                ('cubiertas', models.IntegerField()),
                ('mision', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.cargo')),
                ('nivelPreparacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.nivelpreparacion')),
                ('res272006', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.res272006')),
                ('res492019', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.res492019')),
                ('unidadOrganizativa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.unidadorganizativa')),
            ],
            options={
                'verbose_name': 'Plaza',
                'verbose_name_plural': 'Plazas',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300)),
                ('sexo', models.CharField(max_length=9)),
                ('ci', models.CharField(max_length=11)),
                ('direccionParticular', models.CharField(max_length=1000)),
                ('fechaAlta', models.DateField()),
                ('fechaBaja', models.DateField()),
                ('fuenteProcedencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.fuenteprocedencia')),
                ('motivoBaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.motivobaja')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.plaza')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.provincia'),
        ),
        migrations.CreateModel(
            name='CargoNivelPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.cargo')),
                ('nivelPreparacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.nivelpreparacion')),
            ],
            options={
                'verbose_name': 'Cargo por nivel de preparacion',
                'verbose_name_plural': 'Cargos por nivel de preparacion',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='categoriaOcupacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.categoriaocupacional'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.clasificacion'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='grupoEscala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.grupoescala'),
        ),
    ]
