# Generated by Django 4.1.2 on 2022-11-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaza',
            name='res272006',
        ),
        migrations.RemoveField(
            model_name='plaza',
            name='res492019',
        ),
        migrations.DeleteModel(
            name='Res272006',
        ),
        migrations.DeleteModel(
            name='Res492019',
        ),
    ]
