# Generated by Django 4.1.2 on 2023-01-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_plaza_res272006_remove_plaza_res492019_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoNivelPreparacion',
        ),
    ]
